# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true
  deadline: 5m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - goerr113
    - gochecknoglobals
    - funlen
    - gocognit
    - wrapcheck
    - exhaustivestruct
    - cyclop
    - interfacer
    - maligned

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gomnd
        - goconst
        - paralleltest
        - forbidigo
      path: "_test.go"
