# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 40
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - containedctx
    - goerr113
    - funlen
    - gocognit
    - cyclop
    - lll
    - maligned
    - gochecknoglobals
    - gomnd
    - wrapcheck
    - paralleltest
    - forbidigo
    - exhaustivestruct
    - interfacer # deprecated
    - forcetypeassert
    - scopelint # deprecated
    - ifshort # too many false positives
    - golint # deprecated
    - varnamelen
    - tagliatelle
    - errname
    - ireturn
    - exhaustruct
    - nonamedreturns
    - nosnakecase
    - structcheck
    - varcheck
    - deadcode

issues:
  exclude:
    - "strings.Title is deprecated"
    - "strings.Title has been deprecated"
    - "\"io/ioutil\" has been deprecated"
    - "cyclomatic complexity \\d+ of func `\\(Schema\\).IsTrivial` is high"
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gomnd
        - goconst
        - goerr113
        - noctx
        - funlen
        - dupl
        - structcheck
        - unused
        - unparam
        - nosnakecase
      path: "_test.go"
    - linters:
        - errcheck # Error checking omitted for brevity.
        - errchkjson
      path: "example_"

