# See https://golangci-lint.run/docs/linters/configuration/
version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - containedctx
    - embeddedstructfieldcheck
    - err113
    - maintidx
    - funlen
    - gocyclo
    - gocognit
    - cyclop
    - noinlineerr
    - wsl_v5
    - funcorder
    - copyloopvar
    - depguard
    - dupword
    - errname
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - intrange
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - paralleltest
    - recvcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - varnamelen
    - wrapcheck
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 45
    misspell:
      locale: US
    unparam:
      check-exported: true
    nestif:
      min-complexity: 7
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: strings.Title has been deprecated
      - linters:
          - gosec
          - dupl
          - funlen
          - goconst
          - mnd
          - noctx
          - unparam
          - unused
          - errchkjson
          - err113
        path: _test.go
      - linters:
          - errcheck
          - gosec
        path: example_
      - linters:
          - revive
        text: 'unused-parameter: parameter'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
