language: go

go:
  - tip
  - 1.14.x
  - 1.13.x

script:
  - GO111MODULE=on go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)